### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by piratebroadcast**
Added missing words for readability.

### CODE REVIEW

**Comment by michelson** [comment]
thanks!

**Comment by piratebroadcast** [comment]
I'm about to integrate this into a Rails app for backpackers Im working on,
mind if I shoot you a message if I get into a jam? Hopefully itll all go
smoothly :)

On Tue, Nov 10, 2015 at 1:23 PM, Miguel Michelson Martinez <
notifications@github.com> wrote:

> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michelson/Dante/pull/99#issuecomment-155521836>.
>



-- 
Jesse Waites
JesseWaites.com

**Comment by michelson** [comment]
please be my guest, I will glad to help, good luck with your project!

**Comment by piratebroadcast** [comment]
Awesome, thanks! I actually hit a roadblock with getting it to save to my
@story.new - I'm just not sure how to wire it all together.

I wrote up a reddit post with details here:

https://www.reddit.com/r/rails/comments/3sby6m/someone_mind_giving_me_some_tips_about_saving/

You can also fele free to email me directly at jesse.waites@gmail.com if
you;d like to get this conversation out of GitHub.

Thanks a TON for making this and helping me, it looks so cool and I'm going
to be really proud once I have everything together! I'm kind of a high
level Jr / low level mid Rails developer so I'm working on a new project to
have something to show off to future prospective employers. I'm going
backpacking around Europe for 2 weeks and decided a social network for
backpackers would be super cool. I got the domain BCKPCKRS.com and am
looking forward to building something that looks great! Itll be a place for
travelers to share their travel stories.



On Tue, Nov 10, 2015 at 9:01 PM, Miguel Michelson Martinez <
notifications@github.com> wrote:

> please be my guest, I will glad to help, good luck with your project!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michelson/Dante/pull/99#issuecomment-155631161>.
>



-- 
Jesse Waites
JesseWaites.com

**Comment by michelson** [comment]
Hi Jesse , check this issue https://github.com/michelson/Dante/issues/76 ,
it will help


Atte.
Miguel Michelson Martinez
www.artenlinea.com

**Pull request merged**
