### PR TITLE
add deleteFile method to Uploader

### PR DESCRIPTION
**Pull request by galki**

### CODE REVIEW

**Comment by michelson** [comment]
Hi @galki , thanks for this.

as is will be not a default behavior this should be configurable.
I've implemented it in #127 and it will work with a callback just before image removal:

```js
<script type="text/javascript">

 delete_handler = function(data){
  // do your thing
 }

 editor = new Dante.Editor(
    {
      api_key: "your_oembed_token",
      el: "#editor",
      image_delete_callback: delete_handler
    }
  )
  editor.start()
</script>
```

**Comment by galki** [comment]
That is a better idea, thank you.

I took a look and the callback has `$(".is-selected").find("img").data()` as an arguement. Can it be `$(".is-selected").find("img")` instead? It would make it easier to get the src value.

**Comment by michelson** [comment]
I don't know if this would be a good idea , because the element will be destroyed, so maybe is better to save the src in data attributes (data-src ) and pass only the data hash to the proc

**Comment by galki** [comment]
That's true. What about passing both the data and src? The reason is src
guarantees a delete so it feels like extra work setting it.

2016年6月14日火曜日、Miguel Michelson Martinez<notifications@github.com>さんは書きました:

**Comment by michelson** [comment]
note that the src will change once the image is uploaded, (not just previewed) so in that stage we could set the src into the data attribute. Then you will receive the entire hash on the delete_image_handler

sounds any good ?

**Comment by galki** [comment]
Yes that sounds good!

2016年6月14日火曜日、Miguel Michelson Martinez<notifications@github.com>さんは書きました:

**Pull request closed without merging**
