### PR TITLE
List support

### PR DESCRIPTION
**Pull request by AdamOstrove**
Introduces basic list support using smart shortcuts. "- ", "1. ", and "1) " can be used at the start of a paragraph to convert it into an unordered or ordered list on the next spacebar or enter keydown. Backspace in the first list item will remove it from the list into its own paragraph. Enter on the last child will break into a new paragraph if that child was empty. 

To-Do:
-Hide media "+" button in empty lists
-Introduce insert (un)ordered list buttons to the pop-up menu
-Merging consecutive lists, as well as split a list into two separate lists.
-Allow Lists to be entered at editor creation (They are currently converted to paragraphs)

### CODE REVIEW

**Comment by michelson** [comment]
Hi @AdamOstrove , thanks for your contribution , 
unfortunately I can't merge this , because you made the changes directly on the generated release files , but for development you must change the files that are located in app/assets , these are in coffeescript & scss.
If you don't code in coffee-script give me some days to review your code and port it to coffee.
very good job by the way Sr!

Best!

**Comment by AdamOstrove** [comment]
Sorry about that Miguel. We are working on converting everything now.

**Comment by michelson** [comment]
That's cool! check the Readme on the *Development* section to test the demo in local server

best

**Comment by AdamOstrove** [comment]
@michelson I believe everything has now been put in its proper place. Please look it over and make sure we didn't miss anything. 

Thanks!

**Comment by michelson** [comment]
thanks @AdamOstrove , good job!
I'll review this asap and let you know how it goes

**Comment by michelson** [comment]
Hi @AdamOstrove, @DhavalGandhi, really Nice job!

I´ve reviewed the code and I found some really small issues that I've already fix in a merged branch that takes this PR as starting point.  https://github.com/michelson/Dante/tree/AdamOstrove-list-support. So this feature is almost ready to be merged. But I would like to you to try this out and tell me if it's working properly before merge.

### fixed features:

+ Hides Tooltip.
+ Fix focus on list element when list is created from the enter (return) key.

really good Job!

**Pull request merged**
