### PR TITLE
Allow Default Title and Body

### PR DESCRIPTION
**Pull request by jbolles5**
Add title and body as options for the editor so they can be passed in via the initializer.

### CODE REVIEW

**Comment by michelson** [comment]
Hi @jbolles5 , thanks for this PR.

You can init body content automaticly like this:

```erb
      <div id="editor editable" >
         <%= clean_dante_post( @post.excerpt ).try(:html_safe) %>
     </div>
```

maybe we should just use the title's initialization option and prescind of body's option.

**Comment by jbolles5** [comment]
Makes sense to me. I will remove the body option, leave the title there, and update the read me with your code snippet to make things more clear. I'll let you know when the updated pull request is ready.

**Comment by jbolles5** [comment]
Ok, I think it is all ready to go.

**Comment by michelson** [comment]
Thanks!

**Comment by jbolles5** [comment]
Thank you! The editor is awesome!

**Pull request merged**
