### PR TITLE
add method to option and key for data

### PR DESCRIPTION
**Pull request by talgautb**
by #65

### CODE REVIEW

**Comment by Flyr1Q** [comment]
:+1:  Was looking forward for this, thx!

**Comment by michelson** [comment]
Sorry for the Delay my friend
Looks good to me , I will merge this tonight

thanks for the contribution @talgautb !

**Comment by talgautb** [comment]
ok)
some promlems ?

**Comment by michelson** [comment]
@talgautb , it's merged , check README for the new option , released as 0.0.12

thanks for your contribution

**Pull request merged**
