### PR TITLE
added sanitize option whether clear HTML paste or not

### PR DESCRIPTION
**Pull request by seoyoochan**
I wanted to paste my code as the topic was about technologies, so I needed this option.

### CODE REVIEW

**Comment by michelson** [comment]
Hi @seoyoochan, thanks for this PR.
I think the editor should always must sanitize content, because it could break the interaction.
In the your use case you want to mantain the existing `pre` tags of the pastes code ? or is something else ?

**Comment by seoyoochan** [comment]
My usecase was keeping my code in <pre> or <code> tag and then let Google syntax highlight js or Prismjs highlight the code block

**Comment by michelson** [comment]
Hi @seoyoochan , I don't understand
I will not merge this , because `pre` tags are already whitelisted and formatted and `code` tags are converted to `pre` tags. Finnaly when the sanitize process end the elements will be formated with class names like `.graf.gra--element`
I suggest that you take the `.graf.graf--pre` elements and format with the style or bind the js functions you want.

btw , I've paste your last comment in dante editor , this is the result. 

screen shot 2015-07-27 at 4 47 04 pm

**Comment by seoyoochan** [comment]
@michelson make sense. If that how it works then I agree with you. Hey by the way why Dante can't select multiple lines unlike Medium does. I think it needs to implement mouse down event to get multiple section.

**Pull request closed without merging**
